---
title: "fish_coral_data"
author: ""
date: "2025-05-29"
output: html_document
---


```{r setup, include=FALSE}

library("tidyverse")
library("tictoc")

```




```{r}

# read in Sally Holbrook and Russ Schmitt's survey data
dt <- read.csv("fish_coral_data.csv") 

# calculate coral volume and log scale coral area
dt2 <- dt %>% mutate(coral_vol = 2/3*coral_area.cm2*coral_height.cm, log_coral_area = log(coral_area.cm2)) %>% rename(coral_area = coral_area.cm2)

# View(dt2)

```


```{r}

# checking relationship between volume and number of fish

# plot(x = dt2$coral_vol, y = dt2$Df_tot, las = 1)
# 
# plot(x = dt2$coral_vol, y = dt2$Df_tot + dt2$Da_tot + dt2$Cv_tot, las = 1)


```




Df = Dascyllus flavicaudus (yellowtail)
Cv = Chromis viridis
Da = Dascyllus aruanus (humbug)


# Figure 4


```{r}
Dfcol <-  "#FAE093"
Dacol <- "#2F3D70"
Cvcol <- "#7ACCD7"

cex.f <- 1.2

#pdf("figures/fish_coral.pdf", width = 9, height = 4)
par(mfrow = c(2, 1))
par(mar=c(0, 1.25, 0.5, 1.5), oma = c(3.5, 2.75, 2, 0))
layout(matrix(c(1, 2), nrow = 1, ncol = 2, byrow = F), widths = rep(1, 2), heights = rep(1, 1))

hist(log(dt2$coral_area), col = adjustcolor(col = "#B09771", alpha.f = 0.65), main = NA, xlab = NA, ylab = NA, las = 1, ylim = c(0, 80), xaxt = "n")
#abline(v = pi*7*7, lty = 2)
axis(side = 1, at = log(c(10, 100, 1000, 10000)), labels = c(10, 100, 1000, 10000))
mtext(side = 1, expression(Coral~area~(cm^2)), line = 2.5, cex = 1.25)
mtext(side = 2, "Frequency", line = 2, cex = 1.25)
mtext(side = 3, "A) Host & partner distributions", adj = 0, cex = 1.3)
abline(v = log(pi*7*7), lty = 2)
hist(log(dt2$coral_area[which(dt2$Df_tot + dt2$Da_tot + dt2$Cv_tot >=1)]) , col = adjustcolor(col = "#287DAB", alpha.f = 0.85), add = T)
legend("topleft", legend = c("All corals", "Occupied corals"), fill = c("#B09771","#287DAB"), inset = c(0.01, 0.025), bg = "white")


plot(x = dt2$log_coral_area, y = dt2$Df_tot, las = 1, xlab = NA, ylab = NA, pch = 16, col = adjustcolor(col = Dfcol, alpha.f = 1), cex = cex.f, xaxt = "n", xlim = c(2.25, 9.25), ylim = c(0, max(dt2$Df_tot, dt2$Da_tot, dt2$Cv_tot, na.rm = T)))
mtext(side = 1, expression(Coral~area~(cm^2)), line = 2.5, cex = 1.25)
#mtext(side = 1, "Coral area (log scale)", line = 2.25, cex = 1.25)
mtext(side = 2, "Number of fish", line = 2.5, cex = 1.25)
mtext(side = 3, "B) Partners per host", adj = 0, cex = 1.3)
#axis(side = 1, at = log(c(20, 100, 1000, 5000)), labels = c(20, 100, 1000, 5000))
axis(side = 1, at = log(c(10, 100, 1000, 10000)), labels = c(10, 100, 1000, 10000))
points(x = dt2$log_coral_area, y = dt2$Da_tot, pch = 16, col = adjustcolor(col = Dacol, alpha.f = 0.5), cex = cex.f)
points(x = dt2$log_coral_area, y = dt2$Cv_tot, pch = 16, col = adjustcolor(col = Cvcol, alpha.f = 0.5), cex = cex.f)
abline(v = log(pi*7*7), lty = 2)
legend("topleft", legend = c("Dascyllus flavicaudus", "Dascyllus aruanus", "Chromis viridis"), col = c(Dfcol, Dacol, Cvcol), pch = 16, pt.cex = 1.5, bg = "white")


#dev.off()
```


```{r}

# check the boundaries and proportions occupied
hist1 <- hist(log(dt2$coral_area))
bins1 <- hist1$breaks

# bins1

hist2 <- hist(log(dt2$coral_area[which(dt2$Df_tot + dt2$Da_tot + dt2$Cv_tot >=1)]), breaks = hist1$breaks)

# proportion occupied

round(hist2$counts/hist1$counts, 2)

# so proportions occupied are (0, 0, 0, 0.07, 0.12, 0.44, 0.55, 0.8, 0.95, 0.97, 1, 1)


```


# SM figures

calculate Manly-chesson preferences

```{r}
bin_bounds <- bins1

# relative total areas in different size classes
prop_areas <- rep(NA, length(bin_bounds)-1)

for(i in 1:(length(bin_bounds)-1)){
  
    
    prop_areas[i] <- sum(dt2$coral_area[which(dt2$log_coral_area > bin_bounds[i] & dt2$log_coral_area < bin_bounds[i+1])])/sum(dt2$coral_area)
  
}



# total number of D. flavicaudus in each of these size classes
Df_tots <- rep(NA, length(bin_bounds)-1)

for(i in 1:(length(bin_bounds)-1)){

    Df_tots[i] <- sum(dt2$Df_tot[which(dt2$log_coral_area > bin_bounds[i] & dt2$log_coral_area < bin_bounds[i+1])])
  
}

# repeat for D. aruanus
Da_tots <- rep(NA, length(bin_bounds)-1)

for(i in 1:(length(bin_bounds)-1)){
    
    Da_tots[i] <- sum(dt2$Da_tot[which(dt2$log_coral_area > bin_bounds[i] & dt2$log_coral_area < bin_bounds[i+1])], na.rm = T)
  
}


# repeat for C. viridis
Cv_tots <- rep(NA, length(bin_bounds)-1)

for(i in 1:(length(bin_bounds)-1)){
  
    Cv_tots[i] <- sum(dt2$Cv_tot[which(dt2$log_coral_area > bin_bounds[i] & dt2$log_coral_area < bin_bounds[i+1])], na.rm = T)
    
  
}


# repeat for total number of fish
All_tots <- rep(NA, length(bin_bounds)-1)

for(i in 1:(length(bin_bounds)-1)){
    
    All_tots[i] <- sum(c(dt2$Df_tot[which(dt2$log_coral_area > bin_bounds[i] & dt2$log_coral_area < bin_bounds[i+1])], dt2$Da_tot[which(dt2$log_coral_area > bin_bounds[i] & dt2$log_coral_area < bin_bounds[i+1])], dt2$Cv_tot[which(dt2$log_coral_area > bin_bounds[i] & dt2$log_coral_area < bin_bounds[i+1])]), na.rm = T)
    
  
}



MC_ratios.Df <- Df_tots/prop_areas/(sum(Df_tots/prop_areas, na.rm = T))
MC_ratios.Da <- Da_tots/prop_areas/(sum(Da_tots/prop_areas, na.rm = T))
MC_ratios.Cv <- Cv_tots/prop_areas/(sum(Cv_tots/prop_areas, na.rm = T))

MC_ratios.All <- All_tots/prop_areas/(sum(All_tots/prop_areas, na.rm = T))

# check that these sum to 1
sum(MC_ratios.Df, na.rm = T)
sum(MC_ratios.Da, na.rm = T)
sum(MC_ratios.Cv, na.rm = T)
sum(MC_ratios.All, na.rm = T)

# 1/(length(prop_areas))
# MC_ratios.Df
# 1/(length(prop_areas))
# MC_ratios.Da
# 1/(length(prop_areas))
# MC_ratios.Cv
# 
# 1/(length(prop_areas))
# MC_ratios.All

```

plot this

```{r}
Dfcol <-  "#FAE093"
Dacol <- "#2F3D70"
Cvcol <- "#7ACCD7"
Totcol <-  "#D73202"

# c("Dascyllus flavicaudus", "Dascyllus aruanus", "Chromis viridis")

#pdf("figures/fish_coral_SM.pdf", width = 5, height = 5.75)

par(mfrow = c(2, 1))
par(mar=c(0.1, 1.25, 0.5, 1.5), oma = c(3.5, 2.75, 0.1, 0))
layout(matrix(c(1, 2), nrow = 2, ncol = 1, byrow = F), widths = rep(1, 1), heights = rep(1, 2))

plot(x = bin_bounds[1:(length(bin_bounds)-1)] + 0.5*diff(bin_bounds)[1], y = MC_ratios.Df, type = "o", pch = 16, col = Dfcol, las = 1, ylim = c(0, max(MC_ratios.Df, MC_ratios.Da, MC_ratios.Cv, MC_ratios.All, na.rm = T)), xlab = NA, ylab = NA, xaxt = "n", xlim = c(log(10), log(10000)))
mtext(side = 2, "Preference", line = 2.5)
mtext(side = 3, line = -1, "a) Fish preferences", adj = 0.05)
abline(h = 1/(length(prop_areas)), col = "black", lty = 2)
axis(side = 1, at = log(c(10, 100, 1000, 10000)), labels = NA)
lines(x = bin_bounds[1:(length(bin_bounds)-1)] + 0.5*diff(bin_bounds)[1], y = MC_ratios.Da, type = "o", pch = 16, col = Dacol)
lines(x = bin_bounds[1:(length(bin_bounds)-1)] + 0.5*diff(bin_bounds)[1], y = MC_ratios.Cv, type = "o", pch = 16, col = Cvcol)
lines(x = bin_bounds[1:(length(bin_bounds)-1)] + 0.5*diff(bin_bounds)[1], y = MC_ratios.All, type = "o", pch = 16, col = Totcol)
legend("topleft", legend = c("Dascyllus flavicaudus", "Dascyllus aruanus", "Chromis viridis", "Total"), col = c(Dfcol, Dacol, Cvcol, Totcol), pch = 16, lty = 1, bty = "n", inset = c(0, 0.15), cex = 0.85)

# show coral heights
# check on the largest coral
#bin_bounds
#dt2$log_coral_area[which(dt2$log_coral_area > bin_bounds[length(bin_bounds)-1] & dt2$log_coral_area < bin_bounds[length(bin_bounds)])]

plot(x = dt2$log_coral_area, y = dt2$coral_height, ylim = c(0, max(dt2$coral_height)), pch = 16, xlab = NA, ylab = NA, xaxt = "n", xlim = c(log(10), log(10000)), las = 1, col = adjustcolor("black", alpha.f = 0.6))
mtext(side = 1, expression(Coral~area~(cm^2)), line = 2.25)
mtext(side = 3, line = -1, "b) Coral heights", adj = 0.05)
mtext(side = 2, "Colony height (cm)", line = 2.5)
axis(side = 1, at = log(c(10, 100, 1000, 10000)), labels = c(10, 100, 1000, 10000))
#points(x = dt2$log_coral_area[which(dt2$log_coral_area > bin_bounds[length(bin_bounds)-1] & dt2$log_coral_area < bin_bounds[length(bin_bounds)])], y = dt2$coral_height[which(dt2$log_coral_area > bin_bounds[length(bin_bounds)-1] & dt2$log_coral_area < bin_bounds[length(bin_bounds)])], pch = 1, col = "red", cex = 2)

#dev.off()

```



repeat the above using the same size classes as in the model


```{r}

Amax <- pi*(50/2)^2 # max area of a host
Fmn <- pi*(14/2)^2 # area at which the host becomes reproductively mature
Amin <- pi*(1/2)^2 # minimum area of a host 

A_mids <- c((Amin+Fmn)/2, (0.9*Amax+Fmn)/2, (Amax+0.9*Amax)/2) # used for calculating area occupied

bin_bounds <- log(c(Amin, Fmn, 0.9*Amax, max(dt2$coral_area)))

# relative total areas in different size classes
prop_areas <- rep(NA, length(bin_bounds)-1)

for(i in 1:(length(bin_bounds)-1)){
  
    
    prop_areas[i] <- sum(dt2$coral_area[which(dt2$log_coral_area > bin_bounds[i] & dt2$log_coral_area < bin_bounds[i+1])])/sum(dt2$coral_area)
  
}



# total number of D. flavicaudus in each of these size classes
Df_tots <- rep(NA, length(bin_bounds)-1)

for(i in 1:(length(bin_bounds)-1)){

    Df_tots[i] <- sum(dt2$Df_tot[which(dt2$log_coral_area > bin_bounds[i] & dt2$log_coral_area < bin_bounds[i+1])])
  
}

# repeat for D. aruanus
Da_tots <- rep(NA, length(bin_bounds)-1)

for(i in 1:(length(bin_bounds)-1)){
    
    Da_tots[i] <- sum(dt2$Da_tot[which(dt2$log_coral_area > bin_bounds[i] & dt2$log_coral_area < bin_bounds[i+1])], na.rm = T)
  
}


# repeat for C. viridis
Cv_tots <- rep(NA, length(bin_bounds)-1)

for(i in 1:(length(bin_bounds)-1)){
  
    Cv_tots[i] <- sum(dt2$Cv_tot[which(dt2$log_coral_area > bin_bounds[i] & dt2$log_coral_area < bin_bounds[i+1])], na.rm = T)
    
  
}


# repeat for total number of fish
All_tots <- rep(NA, length(bin_bounds)-1)

for(i in 1:(length(bin_bounds)-1)){
    
    All_tots[i] <- sum(c(dt2$Df_tot[which(dt2$log_coral_area > bin_bounds[i] & dt2$log_coral_area < bin_bounds[i+1])], dt2$Da_tot[which(dt2$log_coral_area > bin_bounds[i] & dt2$log_coral_area < bin_bounds[i+1])], dt2$Cv_tot[which(dt2$log_coral_area > bin_bounds[i] & dt2$log_coral_area < bin_bounds[i+1])]), na.rm = T)
    
  
}



MC_ratios.Df <- Df_tots/prop_areas/(sum(Df_tots/prop_areas, na.rm = T))
MC_ratios.Da <- Da_tots/prop_areas/(sum(Da_tots/prop_areas, na.rm = T))
MC_ratios.Cv <- Cv_tots/prop_areas/(sum(Cv_tots/prop_areas, na.rm = T))

MC_ratios.All <- All_tots/prop_areas/(sum(All_tots/prop_areas, na.rm = T))

# check that these sum to 1
sum(MC_ratios.Df, na.rm = T)
sum(MC_ratios.Da, na.rm = T)
sum(MC_ratios.Cv, na.rm = T)
sum(MC_ratios.All, na.rm = T)

# 1/(length(prop_areas))
# MC_ratios.Df
# 1/(length(prop_areas))
# MC_ratios.Da
# 1/(length(prop_areas))
# MC_ratios.Cv
# 
# 1/(length(prop_areas))
# MC_ratios.All
```


```{r}

# plot with model results
Dcol <- "#7B8BA5"
Ncol <- "#B66A40"


Ppref.N1.evo <- c(0.03056071, 0.39069991, 0.57873937)
Ppref.D1.evo <- c(0.02888623, 0.39186314, 0.57925063)
Ppref.0 <- c(0.1228871, 0.3603216, 0.5167914)

#pdf("figures/model_fish_preferences.pdf", width = 9, height = 4)
par(mfrow = c(2, 1))
par(mar=c(0, 1.25, 0.5, 1.5), oma = c(3.5, 2.75, 2, 0))
layout(matrix(c(1, 2), nrow = 1, ncol = 2, byrow = F), widths = rep(1, 2), heights = rep(1, 1))

plot(x = A_mids, y = Ppref.N1.evo, pch = 16, col = Ncol, las = 1, ylim = c(0, 0.7), type = "o", xlab = NA, ylab = NA, lwd = 3, cex = 1.1)
mtext(side = 1, "Host area", line = 2, outer = T, cex = 1.2)
mtext(side = 2, "Partner preference", line = 2.5, cex = 1.2)
mtext(side = 3, "Model", cex = 1.2)
lines(x = A_mids, y = Ppref.D1.evo, pch = 16, col = Dcol, type = "o", lty = 1, lwd = 2)
lines(x = A_mids, y = Ppref.0, pch = 16, col = "black", type = "o", lty = 1, lwd = 2)
abline(h = 1/length(A_mids), lty = 2)
legend(x = "bottomright", legend = c("Nutritional ESS", "Defensive ESS", "Null"), col = c(Ncol, Dcol, "black"), bty = "n", pch = 16, lty = 1)


plot(x = A_mids, y = MC_ratios.Df, pch = 16, col = Dfcol, las = 1, ylim = c(0, 0.7), type = "o", xlab = NA, ylab = NA, lwd = 3, cex = 1.1)
#mtext(side = 1, "Host area", line = 2)
#mtext(side = 2, "Fish preference", line = 2.5)
mtext(side = 3, "Data", cex = 1.2)
lines(x = A_mids, y = MC_ratios.Da, pch = 16, col = Dacol, type = "o", lty = 1, lwd = 2)
lines(x = A_mids, y = MC_ratios.Cv, pch = 16, col = Cvcol, type = "o", lty = 1, lwd = 2)
lines(x = A_mids, y = MC_ratios.All, pch = 16, col = Totcol, type = "o", lty = 1, lwd = 2)
abline(h = 1/length(A_mids), lty = 2)
legend("bottomright", legend = c("Dascyllus flavicaudus", "Dascyllus aruanus", "Chromis viridis", "Total"), col = c(Dfcol, Dacol, Cvcol, Totcol), pch = 16, lty = 1, bty = "n", cex = 1)

#dev.off()

```





